version: '2'
services:
  proxy_mongo:
    image: mongo
    container_name: proxy_mongo
    hostname: proxy_mongo
    ports:
      - 27017
    volumes:
      - ${COMPOSEROOT}/proxy_mongo/data:/data/db
    command: mongod --directoryperdb

  echo:
    image: solsson/http-echo
    container_name: echo
    hostname: echo
    ports: 
      - 1338
    environment:
      PORT: 1338

  sails_proxy:
    depends_on:
      - proxy_mongo
      - echo
    image: twhtanghk/sails_proxy
    container_name: sails_proxy
    hostname: sails_proxy
    ports:
      - 1337
    env_file: .env
    environment:
      NODE_ENV: development
